# Generated by Django 2.2 on 2020-01-04 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20200104_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='last_name',
        ),
    ]
